/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours/$slug': typeof ToursSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cancellation-policy' | '/sitemap.xml' | '/tours/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cancellation-policy' | '/sitemap.xml' | '/tours/$slug'
  id:
    | '__root__'
    | '/'
    | '/cancellation-policy'
    | '/sitemap.xml'
    | '/tours/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToursSlugRoute: typeof ToursSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToursSlugRoute: ToursSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
